# Generated by Django 2.0.6 on 2018-07-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='emails',
            new_name='email',
        ),
    ]
