# Generated by Django 2.0.6 on 2018-07-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180702_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_stuff',
            field=models.BooleanField(default=False),
        ),
    ]
