# Generated by Django 2.0.6 on 2018-07-02 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_is_stuff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
