# Generated by Django 2.0.6 on 2018-06-17 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='slug',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
