# Generated by Django 2.0.6 on 2018-06-20 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180619_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('post_text', models.TextField()),
                ('published_date', models.DateTimeField(verbose_name=datetime.datetime(2018, 6, 19, 20, 47, 14, 484705))),
            ],
        ),
    ]
