# Generated by Django 2.0.6 on 2018-07-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='poster',
            new_name='commenter',
        ),
    ]
