# Generated by Django 2.0.6 on 2018-06-26 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment_comment_tree'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('comment_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_comment_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
