# Generated by Django 2.0.6 on 2018-06-26 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180626_1343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Comment_Tree',
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
