# Generated by Django 2.0.6 on 2018-06-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180626_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comment_tree',
        ),
    ]
