# Generated by Django 2.0.6 on 2018-06-26 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_post_post_comment_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Post'),
        ),
    ]
