# Generated by Django 2.0.6 on 2018-06-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_node_post_tree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_Node',
        ),
        migrations.DeleteModel(
            name='Post_Tree',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_parent',
        ),
    ]
