# Generated by Django 2.0.6 on 2018-06-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180626_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
