# Generated by Django 2.0.6 on 2018-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_delete_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='post_delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
